
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frcvqodsxekrrsfeihfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyY3Zxb2RzeGVrcnJzZmVpaGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NjMzNzQsImV4cCI6MjA1NzUzOTM3NH0.ZnhX9jvnXhyw2pvMomoZGDzBiqzh8aqS-DjasZaU8ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
